from ctypes import _Pointer
from typing import Any, ClassVar, TypeAlias

from .depend import WAVEFORMATEX

_GUID: TypeAlias = Any  # actually comtypes.GUID
_IUnknown: TypeAlias = Any  # actually comtypes.IUnknown

class ISimpleAudioVolume(_IUnknown):
    _iid_: ClassVar[_GUID]
    def SetMasterVolume(self, fLevel: float, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def GetMasterVolume(self) -> float: ...
    def SetMute(self, bMute: int, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def GetMute(self) -> int: ...

class IAudioClient(_IUnknown):
    _iid_: ClassVar[_GUID]
    def Initialize(
        self,
        ShareMode: int,
        StreamFlags: int,
        hnsBufferDuration: int,
        hnsPeriodicity: int,
        pFormat: WAVEFORMATEX | _Pointer[WAVEFORMATEX],
        AudioSessionGuid: _GUID | _Pointer[_GUID] | None,
    ) -> int: ...
    def GetBufferSize(self) -> int: ...
    def GetStreamLatency(self) -> int: ...
    def GetCurrentPadding(self) -> int: ...
    def IsFormatSupported(self, ShareMode: int, pFormat: WAVEFORMATEX | _Pointer[WAVEFORMATEX]) -> _Pointer[WAVEFORMATEX]: ...
    def GetMixFormat(self) -> _Pointer[WAVEFORMATEX]: ...
    def GetDevicePeriod(self) -> tuple[int, int]: ...
    def Start(self) -> int: ...
    def Stop(self) -> int: ...
    def Reset(self) -> int: ...
    def SetEventHandle(self, eventHandle: int | None) -> int: ...
    def GetService(self, iid: _GUID | _Pointer[_GUID]) -> _IUnknown: ...

class IChannelAudioVolume(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetChannelCount(self) -> int: ...
    def SetChannelVolume(self, dwIndex: int, fLevel: float, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def GetChannelVolume(self, dwIndex: int) -> float: ...
