from ctypes import _Pointer, c_float
from typing import Any, TypeAlias

from pycaw.api.audiopolicy import IAudioSessionControl
from pycaw.api.endpointvolume.depend import PAUDIO_VOLUME_NOTIFICATION_DATA
from pycaw.api.mmdeviceapi.depend.structures import PROPERTYKEY
from pycaw.utils import AudioSession

_GUID: TypeAlias = Any  # actually comtypes.GUID
_COMObject: TypeAlias = Any  # actually comtypes.COMObject

class AudioSessionNotification(_COMObject):
    def __init__(self) -> None: ...
    def OnSessionCreated(self, new_session: IAudioSessionControl) -> None: ...
    def on_session_created(self, new_session: AudioSession) -> None: ...

class AudioSessionEvents(_COMObject):
    def __init__(self) -> None: ...
    AudioSessionState: tuple[str, ...]
    AudioSessionDisconnectReason: tuple[str, ...]
    def OnDisplayNameChanged(self, new_display_name: str, event_context: _Pointer[_GUID]) -> None: ...
    def OnIconPathChanged(self, new_icon_path: str, event_context: _Pointer[_GUID]) -> None: ...
    def OnSimpleVolumeChanged(self, new_volume: float, new_mute: int, event_context: _Pointer[_GUID]) -> None: ...
    def OnChannelVolumeChanged(
        self,
        channel_count: int,
        new_channel_volume_array: _Pointer[c_float],
        changed_channel: int,
        event_context: _Pointer[_GUID],
    ) -> None: ...
    def OnGroupingParamChanged(self, new_grouping_param: _Pointer[_GUID], event_context: _Pointer[_GUID]) -> None: ...
    def OnStateChanged(self, new_state_id: int) -> None: ...
    def OnSessionDisconnected(self, disconnect_reason_id: int) -> None: ...
    def on_display_name_changed(self, new_display_name: str, event_context: _Pointer[_GUID]) -> None: ...
    def on_icon_path_changed(self, new_icon_path: str, event_context: _Pointer[_GUID]) -> None: ...
    def on_simple_volume_changed(self, new_volume: float, new_mute: int, event_context: _Pointer[_GUID]) -> None: ...
    def on_channel_volume_changed(
        self, channel_count: int, new_channel_volume_array: list[float], changed_channel: int, event_context: _Pointer[_GUID]
    ) -> None: ...
    def on_grouping_param_changed(self, new_grouping_param: _Pointer[_GUID], event_context: _Pointer[_GUID]) -> None: ...
    def on_state_changed(self, new_state: str, new_state_id: int) -> None: ...
    def on_session_disconnected(self, disconnect_reason: str, disconnect_reason_id: int) -> None: ...

class AudioEndpointVolumeCallback(_COMObject):
    def __init__(self) -> None: ...
    def OnNotify(self, pNotify: PAUDIO_VOLUME_NOTIFICATION_DATA) -> None: ...
    def on_notify(
        self, new_volume: float, new_mute: int, event_context: _Pointer[_GUID], channels: int, channel_volumes: list[float]
    ) -> None: ...

class MMNotificationClient(_COMObject):
    def __init__(self) -> None: ...
    DeviceStates: dict[int, str]
    Roles: list[str]
    DataFlow: list[str]
    def OnDefaultDeviceChanged(self, flow_id: int, role_id: int, default_device_id: str | None) -> None: ...
    def OnDeviceAdded(self, added_device_id: str) -> None: ...
    def OnDeviceRemoved(self, removed_device_id: str) -> None: ...
    def OnDeviceStateChanged(self, device_id: str, new_state_id: int) -> None: ...
    def OnPropertyValueChanged(self, device_id: str, property_struct: PROPERTYKEY) -> None: ...
    def on_default_device_changed(
        self, flow: str, flow_id: int, role: str, role_id: int, default_device_id: str | None
    ) -> None: ...
    def on_device_added(self, added_device_id: str) -> None: ...
    def on_device_removed(self, removed_device_id: str) -> None: ...
    def on_device_state_changed(self, device_id: str, new_state: str, new_state_id: int) -> None: ...
    def on_property_value_changed(self, device_id: str, property_struct: PROPERTYKEY, fmtid: _GUID, pid: int) -> None: ...
