from collections.abc import Iterable
from typing import Any, Literal, TypeAlias, overload

import psutil
from pycaw.api.audioclient import IChannelAudioVolume, ISimpleAudioVolume
from pycaw.api.audiopolicy import IAudioSessionControl2, IAudioSessionManager2
from pycaw.api.endpointvolume import IAudioEndpointVolume
from pycaw.api.mmdeviceapi import IMMDevice, IMMDeviceEnumerator
from pycaw.constants import AudioDeviceState, ERole

_GUID: TypeAlias = Any  # actually comtypes.GUID
_COMObject: TypeAlias = Any  # actually comtypes.COMObject

class AudioDevice:
    id: str
    state: AudioDeviceState
    # Values are the results of PROPVARIANT.GetValue(): bool | str | int | None
    properties: dict[str, Any]
    def __init__(self, id: str, state: AudioDeviceState, properties: dict[str, Any], dev: IMMDevice) -> None: ...
    @property
    def FriendlyName(self) -> str | None: ...
    @property
    def EndpointVolume(self) -> IAudioEndpointVolume: ...

    @property
    def volume_percent(self) -> float: ...
    @volume_percent.setter
    def volume_percent(self, percent: float) -> None: ...

    @property
    def AudioSessionManager(self) -> IAudioSessionManager2: ...

class AudioSession:
    def __init__(self, audio_session_control2: IAudioSessionControl2) -> None: ...
    @property
    def Process(self) -> psutil.Process | None: ...
    @property
    def ProcessId(self) -> int: ...
    @property
    def Identifier(self) -> str: ...
    @property
    def InstanceIdentifier(self) -> str: ...
    @property
    def State(self) -> int: ...

    @property
    def GroupingParam(self) -> _GUID: ...
    @GroupingParam.setter
    def GroupingParam(self, value: _GUID) -> None: ...

    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...

    @property
    def IconPath(self) -> str: ...
    @IconPath.setter
    def IconPath(self, value: str) -> None: ...

    @property
    def SimpleAudioVolume(self) -> ISimpleAudioVolume: ...
    def channelAudioVolume(self) -> IChannelAudioVolume: ...
    def register_notification(self, callback: _COMObject) -> None: ...
    def unregister_notification(self) -> None: ...

class AudioUtilities:
    @staticmethod
    def GetSpeakers() -> AudioDevice: ...
    @staticmethod
    def GetMicrophone() -> IMMDevice: ...
    @staticmethod
    def GetAudioSessionManager() -> IAudioSessionManager2: ...
    @staticmethod
    def GetAllSessions() -> list[AudioSession]: ...
    @staticmethod
    def GetProcessSession(id: int) -> AudioSession | None: ...

    @overload
    @staticmethod
    def CreateDevice(dev: None) -> None: ...
    @overload
    @staticmethod
    def CreateDevice(dev: IMMDevice) -> AudioDevice: ...

    @staticmethod
    def GetAllDevices(data_flow: int = 2, device_state: int = 15) -> list[AudioDevice]: ...
    @staticmethod
    def GetDeviceEnumerator() -> IMMDeviceEnumerator: ...

    @overload
    @staticmethod
    def GetEndpointDataFlow(devId: str, outputType: Literal[0] = 0) -> str: ...
    @overload
    @staticmethod
    def GetEndpointDataFlow(devId: str, outputType: Literal[1]) -> int: ...
    @overload
    @staticmethod
    def GetEndpointDataFlow(devId: str, outputType: int) -> str | int: ...

    @staticmethod
    def SetDefaultDevice(devId: str, roles: Iterable[ERole] | None = None) -> None: ...
