from ctypes import _Pointer, c_ulong
from typing import Any, ClassVar, TypeAlias

from .depend import PROPERTYKEY as PROPERTYKEY, IPropertyStore as IPropertyStore

_GUID: TypeAlias = Any  # actually comtypes.GUID
_IUnknown: TypeAlias = Any  # actually comtypes.IUnknown
_COMObject: TypeAlias = Any  # actually comtypes.COMObject

class IMMDevice(_IUnknown):
    _iid_: ClassVar[_GUID]
    def Activate(
        self, iid: _GUID | _Pointer[_GUID], dwClsCtx: int, pActivationParams: c_ulong | _Pointer[c_ulong] | None
    ) -> _IUnknown: ...
    def OpenPropertyStore(self, stgmAccess: int) -> IPropertyStore: ...
    def GetId(self) -> str: ...
    def GetState(self) -> int: ...

class IMMDeviceCollection(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetCount(self) -> int: ...
    def Item(self, nDevice: int) -> IMMDevice: ...
    # Added by comtypes to interfaces that have an Item method
    def __call__(self, nDevice: int) -> IMMDevice: ...
    def __getitem__(self, index: int) -> IMMDevice: ...

class IMMNotificationClient(_IUnknown):
    _iid_: ClassVar[_GUID]
    def OnDeviceStateChanged(self, pwstrDeviceId: str | None, dwNewState: int) -> int: ...
    def OnDeviceAdded(self, pwstrDeviceId: str | None) -> int: ...
    def OnDeviceRemoved(self, pwstrDeviceId: str | None) -> int: ...
    def OnDefaultDeviceChanged(self, flow: int, role: int, pwstrDefaultDeviceId: str | None) -> int: ...
    def OnPropertyValueChanged(self, pwstrDeviceId: str | None, key: PROPERTYKEY) -> int: ...

class IMMDeviceEnumerator(_IUnknown):
    _iid_: ClassVar[_GUID]
    def EnumAudioEndpoints(self, dataFlow: int, dwStateMask: int) -> IMMDeviceCollection: ...
    def GetDefaultAudioEndpoint(self, dataFlow: int, role: int) -> IMMDevice: ...
    def GetDevice(self, pwstrId: str | None) -> IMMDevice: ...
    def RegisterEndpointNotificationCallback(self, pClient: IMMNotificationClient | _COMObject) -> int: ...
    def UnregisterEndpointNotificationCallback(self, pClient: IMMNotificationClient | _COMObject) -> int: ...

class IMMEndpoint(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetDataFlow(self) -> int: ...
