from ctypes import _Pointer, c_float
from typing import Any, ClassVar, TypeAlias

from ..audioclient import ISimpleAudioVolume

_GUID: TypeAlias = Any  # actually comtypes.GUID
_IUnknown: TypeAlias = Any  # actually comtypes.IUnknown
_COMObject: TypeAlias = Any  # actually comtypes.COMObject

class IAudioSessionEvents(_IUnknown):
    _iid_: ClassVar[_GUID]
    def OnDisplayNameChanged(self, NewDisplayName: str | None, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def OnIconPathChanged(self, NewIconPath: str | None, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def OnSimpleVolumeChanged(self, NewVolume: float, NewMute: int, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def OnChannelVolumeChanged(
        self,
        ChannelCount: int,
        NewChannelVolumeArray: _Pointer[c_float],
        ChangedChannel: int,
        EventContext: _GUID | _Pointer[_GUID] | None,
    ) -> int: ...
    def OnGroupingParamChanged(
        self, NewGroupingParam: _GUID | _Pointer[_GUID] | None, EventContext: _GUID | _Pointer[_GUID] | None
    ) -> int: ...
    def OnStateChanged(self, NewState: int) -> int: ...
    def OnSessionDisconnected(self, DisconnectReason: int) -> int: ...

class IAudioSessionControl(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetState(self) -> int: ...
    def GetDisplayName(self) -> str: ...
    def SetDisplayName(self, Value: str | None, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def GetIconPath(self) -> str: ...
    def SetIconPath(self, Value: str | None, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def GetGroupingParam(self) -> _GUID: ...
    def SetGroupingParam(self, Grouping: _GUID | _Pointer[_GUID] | None, EventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def RegisterAudioSessionNotification(self, NewNotifications: IAudioSessionEvents | _COMObject) -> int: ...
    def UnregisterAudioSessionNotification(self, NewNotifications: IAudioSessionEvents | _COMObject) -> int: ...

class IAudioSessionControl2(IAudioSessionControl):
    _iid_: ClassVar[_GUID]
    def GetSessionIdentifier(self) -> str: ...
    def GetSessionInstanceIdentifier(self) -> str: ...
    def GetProcessId(self) -> int: ...
    def IsSystemSoundsSession(self) -> int: ...
    def SetDuckingPreferences(self, optOut: int) -> int: ...

class IAudioSessionEnumerator(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetCount(self) -> int: ...
    def GetSession(self, SessionCount: int) -> IAudioSessionControl: ...

class IAudioSessionManager(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetAudioSessionControl(
        self, AudioSessionGuid: _GUID | _Pointer[_GUID] | None, StreamFlags: int
    ) -> IAudioSessionControl: ...
    def GetSimpleAudioVolume(
        self, AudioSessionGuid: _GUID | _Pointer[_GUID] | None, CrossProcessSession: int
    ) -> ISimpleAudioVolume: ...

class IAudioSessionNotification(_IUnknown):
    _iid_: ClassVar[_GUID]
    def OnSessionCreated(self, NewSession: IAudioSessionControl) -> int: ...

class IAudioVolumeDuckNotification(_IUnknown):
    _iid_: ClassVar[_GUID]
    def OnVolumeDuckNotification(self, sessionID: str | None, countCommunicationSessions: int) -> int: ...
    def OnVolumeUnduckNotification(self, sessionID: str | None) -> int: ...

class IAudioSessionManager2(IAudioSessionManager):
    _iid_: ClassVar[_GUID]
    def GetSessionEnumerator(self) -> IAudioSessionEnumerator: ...
    def RegisterSessionNotification(self, SessionNotification: IAudioSessionNotification | _COMObject) -> int: ...
    def UnregisterSessionNotification(self, SessionNotification: IAudioSessionNotification | _COMObject) -> int: ...
    def RegisterDuckNotification(
        self, SessionID: str | None, duckNotification: IAudioVolumeDuckNotification | _COMObject
    ) -> int: ...
    def UnregisterDuckNotification(self, duckNotification: IAudioVolumeDuckNotification | _COMObject) -> int: ...
