from ctypes import _Pointer
from typing import Any, ClassVar, TypeAlias

from .structures import PROPERTYKEY as PROPERTYKEY, PROPVARIANT as PROPVARIANT

_GUID: TypeAlias = Any  # actually comtypes.GUID
_IUnknown: TypeAlias = Any  # actually comtypes.IUnknown

class IPropertyStore(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetCount(self) -> int: ...
    def GetAt(self, iProp: int) -> PROPERTYKEY: ...
    def GetValue(self, key: PROPERTYKEY | _Pointer[PROPERTYKEY]) -> PROPVARIANT: ...
    def SetValue(self, key: PROPERTYKEY | _Pointer[PROPERTYKEY], propvar: PROPVARIANT | _Pointer[PROPVARIANT]) -> int: ...
    def Commit(self) -> int: ...
