from ctypes import _CArgObject, _Pointer, c_longlong, c_void_p
from typing import Any, ClassVar, TypeAlias

from pycaw.api.mmdeviceapi import PROPERTYKEY
from pycaw.api.mmdeviceapi.depend import PROPVARIANT

_GUID: TypeAlias = Any  # actually comtypes.GUID
_IUnknown: TypeAlias = Any  # actually comtypes.IUnknown
# Values accepted by c_void_p.from_param() that are useful here.
_VoidP: TypeAlias = c_void_p | _Pointer[Any] | _CArgObject | int | None

class IPolicyConfig(_IUnknown):
    _iid_: ClassVar[_GUID]
    def Unused1(self) -> int: ...
    def Unused2(self) -> int: ...
    def Unused3(self) -> int: ...
    def Unused4(self) -> int: ...
    def Unused5(self) -> int: ...
    def Unused6(self) -> int: ...
    def Unused7(self) -> int: ...
    def Unused8(self) -> int: ...
    def GetPropertyValue(self, pwstrDeviceId: str | None, pKey: PROPERTYKEY | _Pointer[PROPERTYKEY]) -> PROPVARIANT: ...
    def SetPropertyValue(
        self, pwstrDeviceId: str | None, pKey: PROPERTYKEY | _Pointer[PROPERTYKEY], pValue: PROPVARIANT | _Pointer[PROPVARIANT]
    ) -> int: ...
    def SetDefaultEndpoint(self, pwstrDeviceId: str | None, role: int) -> int: ...
    def SetEndpointVisibility(self, pwstrDeviceId: str | None, bVisible: int) -> int: ...

class IPolicyConfigVista(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetMixFormat(self, wszDeviceId: str | None) -> int | None: ...
    def GetDeviceFormat(self, wszDeviceId: str | None, bDefault: int) -> int | None: ...
    def SetDeviceFormat(self, wszDeviceId: str | None, pEndpointFormat: _VoidP, mixFormat: _VoidP) -> int: ...
    def GetProcessingPeriod(self, wszDeviceId: str | None, bDefault: int) -> tuple[int, int]: ...
    def SetProcessingPeriod(self, wszDeviceId: str | None, pmftPeriod: c_longlong | _Pointer[c_longlong]) -> int: ...
    def GetShareMode(self, wszDeviceId: str | None) -> int | None: ...
    def SetShareMode(self, wszDeviceId: str | None, mode: _VoidP) -> int: ...
    def GetPropertyValue(self, wszDeviceId: str | None, key: c_void_p | _Pointer[c_void_p]) -> int | None: ...
    def SetPropertyValue(
        self, wszDeviceId: str | None, key: c_void_p | _Pointer[c_void_p], pv: c_void_p | _Pointer[c_void_p]
    ) -> int: ...
    def SetDefaultEndpoint(self, wszDeviceId: str | None, role: int) -> int: ...
    def SetEndpointVisibility(self, wszDeviceId: str | None, bVisible: int) -> int: ...
