from ctypes import _Pointer
from typing import Any, ClassVar, TypeAlias

from .depend import PAUDIO_VOLUME_NOTIFICATION_DATA

_GUID: TypeAlias = Any  # actually comtypes.GUID
_IUnknown: TypeAlias = Any  # actually comtypes.IUnknown
_COMObject: TypeAlias = Any  # actually comtypes.COMObject

class IAudioEndpointVolumeCallback(_IUnknown):
    _iid_: ClassVar[_GUID]
    def OnNotify(self, pNotify: PAUDIO_VOLUME_NOTIFICATION_DATA) -> int: ...

class IAudioEndpointVolume(_IUnknown):
    _iid_: ClassVar[_GUID]
    def RegisterControlChangeNotify(self, pNotify: IAudioEndpointVolumeCallback | _COMObject) -> int: ...
    def UnregisterControlChangeNotify(self, pNotify: IAudioEndpointVolumeCallback | _COMObject) -> int: ...
    def GetChannelCount(self) -> int: ...
    def SetMasterVolumeLevel(self, fLevelDB: float, pguidEventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def SetMasterVolumeLevelScalar(self, fLevel: float, pguidEventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def GetMasterVolumeLevel(self) -> float: ...
    def GetMasterVolumeLevelScalar(self) -> float: ...
    def SetChannelVolumeLevel(self, nChannel: int, fLevelDB: float, pguidEventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def SetChannelVolumeLevelScalar(
        self, nChannel: int, fLevelDB: float, pguidEventContext: _GUID | _Pointer[_GUID] | None
    ) -> int: ...
    def GetChannelVolumeLevel(self, nChannel: int) -> float: ...
    def GetChannelVolumeLevelScalar(self, nChannel: int) -> float: ...
    def SetMute(self, bMute: int, pguidEventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def GetMute(self) -> int: ...
    def GetVolumeStepInfo(self) -> tuple[int, int]: ...
    def VolumeStepUp(self, pguidEventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def VolumeStepDown(self, pguidEventContext: _GUID | _Pointer[_GUID] | None) -> int: ...
    def QueryHardwareSupport(self) -> int: ...
    def GetVolumeRange(self) -> tuple[float, float, float]: ...

class IAudioMeterInformation(_IUnknown):
    _iid_: ClassVar[_GUID]
    def GetPeakValue(self) -> float: ...
